Add a --command argument, allowing to directly call a Django command …
vshn/django-probes pull request #30
Opened 2023-10-08 08:01 UTC by d9pouces

…when databases are ready, without patching the command itself and without loading the django machinery twice.

2023-10-10 06:19 UTC, bittner requested changes
Thank you for your contribution! I like the idea of the command argument.

There are a few things missing only, to make the change complete. Can you please:

- Add tests for the new CLI option
- Explain the command argument in the README

2023-10-10 06:19 UTC, bittner commented on django_probes/management/commands/wait_for_database.py
> +            call_command(command_list[0], *command_list[1:])
This is a bit cryptic for one-time readers. Maybe better like this?

```suggestion
            parts = shlex.split(command)
            executable, params = parts[0], parts[1:]
            call_command(executable, *params)
```

2023-10-16 05:09 UTC, d9pouces commented
done.
Multiple commands can be called (e.g. migrate then runserver)

2023-10-30 09:17 UTC, bittner requested changes
This looks good, very nice! :+1: 

Please, address the remaining comments and the linter complaints.

Please, also add an explanation sentence to the "[Use with Your Own Command](https://github.com/painless-software/django-probes/pull/30/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR84)" section in the README, so that it reads like e.g.

> You can use the `-c` option to immediately execute Django management commands once the database is available.
> 
> Alternatively, ...

Finally, please [squash your commits](https://www.youtube.com/watch?v=V5KrD7CmO4o) and use a [short commit message](https://www.youtube.com/watch?v=_gpNPNMYbVY), and optionally a longer text only afterwards (separated by a blank line).

Then we're ready to merge and I'll happily issue a new release. :rocket:

2023-10-30 09:17 UTC, bittner commented on django_probes/management/commands/wait_for_database.py
> +                            help='execute this command when database is up (can be repeated multiple times).')
```suggestion
                            help='execute this management command when database is up (can be repeated multiple times).')
```

2023-10-30 09:17 UTC, bittner commented on README.rst
> +    execute this Django command when the database is ready.
```suggestion
    execute this Django management command when the database is ready.
```

2023-10-30 09:17 UTC, bittner commented on README.rst
> +    This option can be used multiple times: ``wait_for_database -c 'migrate' -c 'runserver --skip-checks'``
```suggestion
    This option can be used multiple times, e.g. ``wait_for_database -c 'migrate' -c 'runserver --skip-checks'``
```

2025-11-18 06:33 UTC, merged

2025-11-18 06:34 UTC, bittner commented
Thanks for your awesome contribution! :1st_place_medal:  Sorry it took so long.

2025-11-18 18:32 UTC, bittner commented
@d9pouces Do you still use this package?

Would you be so kind and verify that it works for you as intended?

You should be able to install it from the `main` branch using uv or pip.

2025-11-18 18:37 UTC, d9pouces commented
Hello,
I will check your change as soon as possible (probably next week). 
Thanks!

2025-11-26 12:08 UTC, d9pouces commented
Looks fine, thx again!